# Configuration de la connexion MySQL
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/gestionstock?useSSL=false&serverTimezone=UTC
hibernate.connection.username=root
hibernate.connection.password=

# Le dialecte MySQL
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Affiche les requêtes SQL
hibernate.show_sql=true
hibernate.format_sql=true

# C'est la création automatique des tables
hibernate.hbm2ddl.auto=update